# Generated 2026-04-27. nwg-displays will overwrite this if you use it.

monitor = DP-4, 3840x2160@160, 0x0, 1.5
monitor = HDMI-A-2, disable

# Catch-all for any other display that gets plugged in later
monitor = , preferred, auto, 1
